# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-04 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190225_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='timestam',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
