# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-05 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 5, 15, 58, 43, 191083, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
