# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-06 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20191106_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charge',
            new_name='Card',
        ),
    ]
