# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-03 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectviewed',
            old_name='contenttype',
            new_name='content_type',
        ),
    ]
