# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-21 09:37
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description1',
            field=tinymce.models.HTMLField(default=datetime.datetime(2019, 11, 21, 9, 37, 57, 347049, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
