# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-21 09:43
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_description1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description1',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
