# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-22 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20191121_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description1',
        ),
    ]
